### ISSUE TITLE
Include path option is not used when generating in extconf.rb

### ISSUE THREAD

**Issue by zeroalpha** [reidmorrison/rubywmq#10]
extconf.rb did not use the return values of MakeMakeFile#dir_config.
This resulted in GenerateReason, GenerateConst and GenerateStructs always receiving the default include path.

I created a Fix here:
https://github.com/zeroalpha/rubywmq/tree/extconf_fix

**Comment by reidmorrison** [comment]
Excellent, can you send a pull request?

**Comment by zeroalpha** [comment]
https://github.com/reidmorrison/rubywmq/pull/11

This is my first pull request, so if i am doing something wrong or something is missing, please advise
