### ISSUE TITLE
Need help installing in a Windows 7 environment

### ISSUE THREAD

**Issue by murathp** [reidmorrison/rubywmq#13]
Basically, I am getting the following message when I try to install
I have WebSphere MQ installed in C:\Program Files (x86) instead of C:\Program Files

Two questions:
1. What file I need to modify so that RubyWmq looks for WebSphere in my directory?
2. 

My environment is Windows 7 machine with Ruby and Ruby Devkit installed at the following locations:
Ruby is C:\Ruby22-x64
RubyDev kit is C:\Ruby22-x64\RubyDevkit  (I am not sure if 32 vs. 64 bit matters for RubyWmq.
 Here is the error I'm seeing:
tform=ruby
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing rubywmq:
        ERROR: Failed to build gem native extension.

    C:/Ruby22-x64/bin/ruby.exe -r ./siteconf20150529-1740-13y6zjc.rb extconf.rb
checking for cmqc.h... no
checking for main() in -lmqm... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby22-x64/bin/$(RUBY_BASE_NAME)
        --with-mqm-dir
        --without-mqm-dir
        --with-mqm-include
        --without-mqm-include=${mqm-dir}/include
        --with-mqm-lib
        --without-mqm-lib=${mqm-dir}/lib
        --with-mqmlib
        --without-mqmlib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubywmq-2.0.2/ext/generate/generate_reaso
n.rb:6:in `initialize': No such file or directory @ rb_sysopen - C:\Program File
s\IBM\WebSphere MQ\tools\c\include/cmqc.h (Errno::ENOENT)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubywmq-2.0.2/ext/generate/g
enerate_reason.rb:6:in `open'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubywmq-2.0.2/ext/generate/g
enerate_reason.rb:6:in `extract_const'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubywmq-2.0.2/ext/generate/g
enerate_reason.rb:26:in `reason_case'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubywmq-2.0.2/ext/generate/g
enerate_reason.rb:70:in `block in wmq_reason'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubywmq-2.0.2/ext/generate/g
enerate_reason.rb:69:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubywmq-2.0.2/ext/generate/g
enerate_reason.rb:69:in `wmq_reason'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubywmq-2.0.2/ext/generate/g
enerate_reason.rb:224:in `block in generate'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubywmq-2.0.2/ext/generate/g
enerate_reason.rb:224:in `open'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubywmq-2.0.2/ext/generate/g
enerate_reason.rb:224:in `generate'
        from extconf.rb:27:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubywm
q-2.0.2 for inspection.
Results logged to C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0
/rubywmq-2.0.2/gem_make.out

Here is the gem_make.out
C:/Ruby22-x64/bin/ruby.exe -r ./siteconf20150529-1740-13y6zjc.rb extconf.rb
checking for cmqc.h... no
checking for main() in -lmqm... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=C:/Ruby22-x64/bin/$(RUBY_BASE_NAME)
	--with-mqm-dir
	--without-mqm-dir
	--with-mqm-include
	--without-mqm-include=${mqm-dir}/include
	--with-mqm-lib
	--without-mqm-lib=${mqm-dir}/lib
	--with-mqmlib
	--without-mqmlib
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubywmq-2.0.2/ext/generate/generate_reason.rb:6:in `initialize': No such file or directory @ rb_sysopen - C:\Program Files\IBM\WebSphere MQ\tools\c\include/cmqc.h (Errno::ENOENT)
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubywmq-2.0.2/ext/generate/generate_reason.rb:6:in `open'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubywmq-2.0.2/ext/generate/generate_reason.rb:6:in `extract_const'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubywmq-2.0.2/ext/generate/generate_reason.rb:26:in `reason_case'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubywmq-2.0.2/ext/generate/generate_reason.rb:70:in `block in wmq_reason'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubywmq-2.0.2/ext/generate/generate_reason.rb:69:in `each'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubywmq-2.0.2/ext/generate/generate_reason.rb:69:in `wmq_reason'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubywmq-2.0.2/ext/generate/generate_reason.rb:224:in `block in generate'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubywmq-2.0.2/ext/generate/generate_reason.rb:224:in `open'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubywmq-2.0.2/ext/generate/generate_reason.rb:224:in `generate'
	from extconf.rb:27:in `<main>'

extconf failed, exit code 1

Do you see anything else I am missing?

**Comment by reidmorrison** [comment]
Can you try out the latest V2.1. I tested it on Windows 7 64bit and it works great with:
```
gem install rubywmq
```

Please re-open this ticket if you have issues installing V2.1

**Comment by murathp** [comment]
Hello Reid,

I need some minor clarification/ additional information from you with respect to your environment:

1. What version of Ruby and ruby devkit do you have installed in your environment? I am assuming that you have the 64-bit Ruby 2.2.2 and 64 bit of the ruby devkit installed.

2. Does it matter if I use 32-bit ruby across the board? or better yet, may I use a 32-bit version of Ruby and Ruby Devkit?

The reason for these two questions is I'm still doing something wrong, I fear...I started with 32-bit versions of Windows, Ruby, and Ruby Devkit ...and in the installation failed:

Here is the general approach I followed:

1. Installed Ruby 2.2.2 32-bit
2. Installed Ruby Devkit 2.2.2  (Then initialized, and installed properly) 32-bit
3. Installed/Updated gem installer.
4. Followed your advice and used 
gem install rubywmq-2.1.0.gem

If you like I can send you the error messages I'm seeing in a separate email.

Lets first start clarifying the differences in our environments.  My goal is the replicate your environment as much as I can do so that we can determine, which step I'm messing up during the install.

Thank you so much in advanced.

Murat

 







Date: Mon, 17 Aug 2015 21:18:19 -0700

**Comment by reidmorrison** [comment]
I did everything with 64 bit versions of Ruby, Windows and MQ.

**Comment by murathp** [comment]
Reid,

Which version of the IBM MQ you have installed in your environment?

I want to make sure I have the correct IBM Websphere installed ?

Thanks,

M

Date: Thu, 20 Aug 2015 05:01:41 -0700

**Comment by reidmorrison** [comment]
Both MQ V7.5 and V8. They are freely available for dev use at: https://www.ibm.com/developerworks/community/blogs/messaging/entry/develop_on_websphere_mq_advanced_at_no_charge?lang=en#

**Comment by murathp** [comment]
Hello Reid,

Thank you so much for your help, I finally got it installed without any problems.
So that you know I tried it both on Windows 7 and Windows 10 64-bit w/o any issues so far.

I hope you realize that you have developed a one of a kind product which is very important to not only using MQ from Ruby but also for developing test automation scripts.

Please keep supporting this great product and thank you so much for your hard work.

Murat
Date: Fri, 21 Aug 2015 06:37:46 -0700
